#ifndef OUTPUT_H__
#define OUTPUT_H__

#include "uv_tty.h"


enum {
	SGR_RESET = 0,
	SGR_NORMAL = 0,
	SGR_BOLD,
	SGR_FAINT,
	SGR_ITALIC,
	SGR_UNDERLINE,
	SGR_BLINK_SLOW,
	SGR_BLINK_RAPID,

	SGR_DEFAULT_FONT,

	SGR_BLINK_OFF,

	SGR_COLOR_BLACK,
	SGR_COLOR_RED,
	SGR_COLOR_GREEN,
	SGR_COLOR_YELLOW,
	SGR_COLOR_BLUE,
	SGR_COLOR_MAGENTA,
	SGR_COLOR_CYAN,
	SGR_COLOR_WHITE,
	SGR_COLOR_DEFAULT,

	SGR_COLOR_BLACK_BG,
	SGR_COLOR_RED_BG,
	SGR_COLOR_GREEN_BG,
	SGR_COLOR_YELLOW_BG,
	SGR_COLOR_BLUE_BG,
	SGR_COLOR_MAGENTA_BG,
	SGR_COLOR_CYAN_BG,
	SGR_COLOR_WHITE_BG,
	SGR_COLOR_DEFAULT_BG,
	SGR_MAX
} typedef SGR;

extern void
say (const char *fmt, ...);

extern char *
create_csi (SGR options[], int count);

#endif /* OUTPUT_H__ */
